export const symbols = {
  "HAMMER" : "🔨",
  "RAINDROP" : "💧",
  "TOPGUN" : "🎖️",
  "MASK" : "🎭",
  "CAMEL" : "🐪",
  "CANOPY" : "🌲",
  "LIGHTHOUSE" : "🗼",
  "BARREL" : "🛢️",
  "HORSESHOE" : "🧲",
  "SOUP" : "🥣",
  "LIGHTNING" : "⚡️",
  "TORCH" : "🔥",
  "TARGET" : "🎯",
  "TEAPOT" : "🫖",
  "SAW" : "🪚",
  "SATURN" : "🪐",
  "SCALES" : "⚖️",
  "BOOK" : "📚",
  "COURTHOUSE" : "🏠",
  "TORAH": "📜",
  "LYRE" : "🎻",
  "FEATHER" : "🪶",
  "FORT" : "🏰",
  "SPARTAN": "🤺",
}